[http]
listen_address = "0.0.0.0"
listen_port = 3000

[therma]
tty_path = "/dev/serial/by-id/usb-1a86_USB2.0-Ser_-if00-port0"
slave_id = 1
timeout_ms = 1000

[influx]
url = "http://localhost"
port = "8086"
db = ""
user = "root"
password = ""
id = "hvac"
delta_t_sec = 10

[mqtt]
client_name = "hvac"
host_name = "127.0.0.1"
host_port = 1883
topic = "homeassistant"
username = "frick"
password = "aababc"
channel_size = 2
